# Generated by Django 3.1.7 on 2021-10-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0166_auto_20211009_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followuser',
            old_name='follUser',
            new_name='avatar',
        ),
        migrations.RenameField(
            model_name='followuser',
            old_name='folPr',
            new_name='profiles',
        ),
        migrations.AlterField(
            model_name='profile',
            name='fullName',
            field=models.CharField(blank=True, default='ZfNQe', max_length=221),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, default='aLZOjblH', max_length=250, unique=True),
        ),
    ]
