# Generated by Django 3.1.7 on 2021-10-12 07:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0167_auto_20211012_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favourite',
        ),
        migrations.AddField(
            model_name='profile',
            name='follow',
            field=models.ManyToManyField(blank=True, default=None, related_name='followUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fullName',
            field=models.CharField(blank=True, default='ulLqf', max_length=221),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, default='tWr4xMvN', max_length=250, unique=True),
        ),
    ]
