# Generated by Django 3.1.7 on 2021-08-15 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210815_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='languageC',
            new_name='languageCode',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='languageN',
            new_name='languageName',
        ),
    ]
