# Generated by Django 3.1.7 on 2021-10-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20211009_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='languageCode',
            field=models.CharField(blank=True, choices=[('ar', 'Arabic'), ('en', 'English')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
    ]
