# Generated by Django 3.1.7 on 2021-10-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20211023_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slugLang',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='slugLang',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
