# Generated by Django 3.1.7 on 2021-06-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='LANGUAGES',
            field=models.CharField(choices=[('ar', 'Arabic')], default='arabic', max_length=10),
        ),
    ]
