# Generated by Django 3.1.7 on 2021-06-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_topic_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='LANGUAGES',
            field=models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], default='ar', max_length=10),
        ),
    ]
