# Generated by Django 3.1.7 on 2021-06-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20210623_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='content_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='content_en',
            field=models.TextField(null=True),
        ),
    ]
