# Generated by Django 3.1.7 on 2021-06-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20210623_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='slug_ar',
            field=models.SlugField(max_length=250, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='slug_en',
            field=models.SlugField(max_length=250, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='title_ar',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='title_en',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
