# Generated by Django 3.1.7 on 2021-08-14 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20210623_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='content_ar',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='slug_ar',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='title_en',
        ),
    ]
