# Generated by Django 3.1.7 on 2021-10-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_auto_20211009_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='nm',
            field=models.CharField(default='2', max_length=10),
        ),
    ]
