# Generated by Django 3.1.7 on 2021-10-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_auto_20211009_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slugLang',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='slugLang',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
